apiVersion: v1
kind: Service
metadata:
  name: department-service
  namespace: springboottest
spec:
  selector:
    app: department
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082