apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: springboottest
spec:
  selector:
    app: employee
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
