apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
  namespace: springboottest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - name: employee
        image: ritikumar38921/employee:latest
        ports:
        - containerPort: 8081