apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: springboottest
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007