apiVersion: v1
kind: Service
metadata:
  name: organization-service
  namespace: springboottest
spec:
  selector:
    app: organization
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083