server:
   port: 8081

spring:
   application:
      name: EmployeeApplication
   datasource:
      url: jdbc:postgresql://postgres-service:5432/${POSTGRES_DB}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
      show-sql: true
      hibernate:
         ddl-auto: update