server:
   port: 8080

spring:
   application:
      name: GatewayApplication

   cloud:
      kubernetes:
         discovery:
            enabled: true
      gateway:
         discovery:
            enabled: true
         routes:
         -  id: employee-service
            uri: lb://EmployeeApplication
            predicates:
            -  path: /api/employees/**

         -  id: department-service
            uri: lb://DepartmentApplication
            predicates:
            -  path: /api/departments/**

         -  id: organization-service
            uri: lb://OrganizationApplication
            predicates:
            -  path: /api/organization/**

management:
   endpoints:
      web:
         exposure:
            include: health,info,prometheus,gateway