server:
   port: 8080

spring:
   application:
      name: GatewayApplication
   
   cloud:
      kubernetes:
         discovery:
            enabled: true
      gateway:
         discovery:
            enabled: true
         routes:
           - id: employee-service
             uri: lb://EmployeeApplication
             predicates:
                - path: /api/employee/*
             filters:
                